"""Verify the generated static safety-monitor demonstration offline."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from dataclasses import asdict, dataclass
from html.parser import HTMLParser
from pathlib import Path
from typing import Literal

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from oscillink_safety_ops.benchmark import verify_benchmark  # noqa: E402
from scripts.generate_demo import canonical_json, generate_demo  # noqa: E402

REQUIRED_FILES = {
    "assets/app.js",
    "assets/data.json",
    "assets/oscillink-logo.png",
    "assets/styles.css",
    "index.html",
}
FORBIDDEN_TAGS = {"button", "form", "input", "textarea"}
FORBIDDEN_SCRIPT_TOKENS = (
    "fetch(",
    "xmlhttprequest",
    "websocket",
    "eventsource",
    "sendbeacon",
    "rtcpeerconnection",
    "eval(",
    "exec(",
    "new function",
    "innerhtml",
    "insertadjacenthtml",
    "document.write",
)


class DemoVerificationError(ValueError):
    """Stable fail-closed generated-demo verification error."""

    def __init__(self, code: str, message: str | None = None) -> None:
        self.code = code
        super().__init__(message or code)


@dataclass(frozen=True, slots=True)
class DemoVerification:
    """Verified static-demo totals and boundary state."""

    total_cases: int
    exact_matches: int
    control_surfaces: int
    network_accessed: Literal[False] = False


class _SurfaceParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.control_surfaces = 0
        self.external_resources: list[str] = []
        self.event_attributes: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        if tag in FORBIDDEN_TAGS:
            self.control_surfaces += 1
        for name, value in attrs:
            if name.startswith("on"):
                self.event_attributes.append(name)
            if name in {"src", "href", "action"} and value is not None:
                if value.startswith(("http:", "https:", "//", "data:")):
                    self.external_resources.append(value)
        if tag == "select" and attributes.get("id") != "scenario-select":
            self.control_surfaces += 1


def _sha256(raw: bytes) -> str:
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def _files(root: Path) -> dict[str, bytes]:
    if not root.is_dir() or root.is_symlink():
        raise DemoVerificationError("invalid_root", "demo root must be a real directory")
    result: dict[str, bytes] = {}
    for path in root.rglob("*"):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            raise DemoVerificationError("symlink", f"demo symlink is forbidden: {relative}")
        if path.is_file():
            result[relative] = path.read_bytes()
    if set(result) != REQUIRED_FILES:
        raise DemoVerificationError(
            "file_set", f"demo file set differs: {sorted(set(result) ^ REQUIRED_FILES)}"
        )
    return result


def _verify_payload(raw: bytes) -> dict[str, object]:
    try:
        data = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise DemoVerificationError("data_contract", "demo data is malformed JSON") from error
    if not isinstance(data, dict) or data.get("demo_format") != "oscillink-safety-monitor-demo-v1":
        raise DemoVerificationError("data_contract", "demo data identity is invalid")
    payload_sha256 = data.get("payload_sha256")
    payload = dict(data)
    payload.pop("payload_sha256", None)
    if payload_sha256 != _sha256(canonical_json(payload)):
        raise DemoVerificationError("data_hash", "demo data payload identity drifted")
    cases = data.get("cases")
    metrics = data.get("metrics")
    if not isinstance(cases, list) or len(cases) != 36 or not isinstance(metrics, dict):
        raise DemoVerificationError("data_contract", "demo must bind all 36 benchmark cases")
    if metrics.get("total_cases") != 36 or metrics.get("exact_matches") != 36:
        raise DemoVerificationError("data_contract", "demo metrics are not exact")
    return data


def verify_demo(
    demo_root: Path, *, benchmark_root: Path, repository_root: Path
) -> DemoVerification:
    """Verify benchmark binding, generated bytes, and the read-only static surface."""

    benchmark = verify_benchmark(benchmark_root, repository_root=repository_root)
    actual = _files(demo_root)
    with tempfile.TemporaryDirectory(prefix="oscillink-demo-verify-") as temporary:
        expected_root = Path(temporary) / "demo"
        generate_demo(
            expected_root,
            benchmark_root=benchmark_root,
            source_repository=repository_root,
        )
        expected = _files(expected_root)
    for relative in sorted(REQUIRED_FILES):
        if actual[relative] != expected[relative]:
            raise DemoVerificationError("asset_drift", f"generated asset drifted: {relative}")

    data = _verify_payload(actual["assets/data.json"])
    html = actual["index.html"].decode("utf-8", errors="strict")
    script = actual["assets/app.js"].decode("utf-8", errors="strict")
    parser = _SurfaceParser()
    parser.feed(html)
    if parser.control_surfaces or parser.event_attributes:
        raise DemoVerificationError("control_surface", "demo contains a command/form surface")
    if parser.external_resources:
        raise DemoVerificationError("network_surface", "demo contains an external resource")
    lowered = script.lower()
    if any(token in lowered for token in FORBIDDEN_SCRIPT_TOKENS):
        raise DemoVerificationError(
            "dynamic_surface", "demo script contains a network/dynamic surface"
        )
    if html.count('<select id="scenario-select"') != 1:
        raise DemoVerificationError("selector_contract", "demo scenario selector is invalid")
    if "No physical stop established" not in html:
        raise DemoVerificationError("required_copy", "physical-stop boundary copy is missing")
    if data.get("evidence_label") != "SYNTHETIC EVIDENCE — SOFTWARE BEHAVIOR ONLY":
        raise DemoVerificationError("required_copy", "synthetic evidence label drifted")
    return DemoVerification(
        total_cases=benchmark.total_cases,
        exact_matches=benchmark.exact_matches,
        control_surfaces=parser.control_surfaces,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("demo_root", nargs="?", type=Path, default=ROOT / "demo")
    parser.add_argument("--benchmark-root", type=Path, default=ROOT / "benchmark" / "robot_cell_v1")
    parser.add_argument("--repository-root", type=Path, default=ROOT)
    args = parser.parse_args()
    print(
        json.dumps(
            asdict(
                verify_demo(
                    args.demo_root,
                    benchmark_root=args.benchmark_root,
                    repository_root=args.repository_root,
                )
            ),
            sort_keys=True,
            separators=(",", ":"),
        )
    )


if __name__ == "__main__":
    main()
